name: icon_gallery
description: "A flutter package for picking icon from material icons or your own icons."
version: 0.0.2
homepage: https://github.com/PersianFlutter/icon_gallery
repository: https://github.com/PersianFlutter/icon_gallery

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0


