name: icon_gallery
description: "A flutter package for picking icon from material icons or your own icons."
version: 0.0.1
homepage: https://github.com/PersianFlutter/iconpicker
repository: https://github.com/PersianFlutter/iconpicker

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
